// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spectacle/SpecificationStep.proto

package io.gianluigip.spectacle.events;

public final class SpecificationStep {
  private SpecificationStep() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spectacle_events_SpecificationStepProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spectacle_events_SpecificationStepProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!spectacle/SpecificationStep.proto\022\020spe" +
      "ctacle.events\"k\n\026SpecificationStepProto\022" +
      "-\n\004type\030\001 \001(\0162\037.spectacle.events.StepTyp" +
      "eProto\022\023\n\013description\030\002 \001(\t\022\r\n\005index\030\003 \001" +
      "(\005*2\n\rStepTypeProto\022\t\n\005GIVEN\020\000\022\014\n\010WHENEV" +
      "ER\020\001\022\010\n\004THEN\020\002B\"\n\036io.gianluigip.spectacl" +
      "e.eventsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_spectacle_events_SpecificationStepProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spectacle_events_SpecificationStepProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spectacle_events_SpecificationStepProto_descriptor,
        new String[] { "Type", "Description", "Index", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
