// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spectacle/SpecificationStatus.proto

package io.gianluigip.spectacle.events;

public final class SpecificationStatus {
  private SpecificationStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n#spectacle/SpecificationStatus.proto\022\020s" +
      "pectacle.events*R\n\017SpecStatusProto\022\017\n\013IM" +
      "PLEMENTED\020\000\022\031\n\025PARTIALLY_IMPLEMENTED\020\001\022\023" +
      "\n\017NOT_IMPLEMENTED\020\002B\"\n\036io.gianluigip.spe" +
      "ctacle.eventsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
