// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spectacle/SpecificationStatus.proto

package io.gianluigip.spectacle.events;

/**
 * Protobuf enum {@code spectacle.events.SpecStatusProto}
 */
public enum SpecStatusProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>IMPLEMENTED = 0;</code>
   */
  IMPLEMENTED(0),
  /**
   * <code>PARTIALLY_IMPLEMENTED = 1;</code>
   */
  PARTIALLY_IMPLEMENTED(1),
  /**
   * <code>NOT_IMPLEMENTED = 2;</code>
   */
  NOT_IMPLEMENTED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>IMPLEMENTED = 0;</code>
   */
  public static final int IMPLEMENTED_VALUE = 0;
  /**
   * <code>PARTIALLY_IMPLEMENTED = 1;</code>
   */
  public static final int PARTIALLY_IMPLEMENTED_VALUE = 1;
  /**
   * <code>NOT_IMPLEMENTED = 2;</code>
   */
  public static final int NOT_IMPLEMENTED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static SpecStatusProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SpecStatusProto forNumber(int value) {
    switch (value) {
      case 0: return IMPLEMENTED;
      case 1: return PARTIALLY_IMPLEMENTED;
      case 2: return NOT_IMPLEMENTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SpecStatusProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SpecStatusProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SpecStatusProto>() {
          public SpecStatusProto findValueByNumber(int number) {
            return SpecStatusProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return SpecificationStatus.getDescriptor().getEnumTypes().get(0);
  }

  private static final SpecStatusProto[] VALUES = values();

  public static SpecStatusProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SpecStatusProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:spectacle.events.SpecStatusProto)
}

