// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spectacle/SpecificationUpdated.proto

package io.gianluigip.spectacle.events;

/**
 * Protobuf type {@code spectacle.events.SpecificationUpdatedProto}
 */
public final class SpecificationUpdatedProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:spectacle.events.SpecificationUpdatedProto)
    SpecificationUpdatedProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpecificationUpdatedProto.newBuilder() to construct.
  private SpecificationUpdatedProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpecificationUpdatedProto() {
    name_ = "";
    component_ = "";
    description_ = "";
    status_ = 0;
    steps_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpecificationUpdatedProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpecificationUpdatedProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            component_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            description_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              steps_ = new java.util.ArrayList<SpecificationStepProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            steps_.add(
                input.readMessage(SpecificationStepProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        steps_ = java.util.Collections.unmodifiableList(steps_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SpecificationUpdated.internal_static_spectacle_events_SpecificationUpdatedProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SpecificationUpdated.internal_static_spectacle_events_SpecificationUpdatedProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SpecificationUpdatedProto.class, Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPONENT_FIELD_NUMBER = 2;
  private volatile Object component_;
  /**
   * <code>string component = 2;</code>
   * @return The component.
   */
  @Override
  public String getComponent() {
    Object ref = component_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      component_ = s;
      return s;
    }
  }
  /**
   * <code>string component = 2;</code>
   * @return The bytes for component.
   */
  @Override
  public com.google.protobuf.ByteString
      getComponentBytes() {
    Object ref = component_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      component_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile Object description_;
  /**
   * <code>string description = 3;</code>
   * @return Whether the description field is set.
   */
  @Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @Override
  public String getDescription() {
    Object ref = description_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    Object ref = description_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <code>.spectacle.events.SpecStatusProto status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  @Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.spectacle.events.SpecStatusProto status = 4;</code>
   * @return The status.
   */
  @Override public SpecStatusProto getStatus() {
    @SuppressWarnings("deprecation")
    SpecStatusProto result = SpecStatusProto.valueOf(status_);
    return result == null ? SpecStatusProto.UNRECOGNIZED : result;
  }

  public static final int STEPS_FIELD_NUMBER = 5;
  private java.util.List<SpecificationStepProto> steps_;
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  @Override
  public java.util.List<SpecificationStepProto> getStepsList() {
    return steps_;
  }
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  @Override
  public java.util.List<? extends SpecificationStepProtoOrBuilder>
      getStepsOrBuilderList() {
    return steps_;
  }
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  @Override
  public int getStepsCount() {
    return steps_.size();
  }
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  @Override
  public SpecificationStepProto getSteps(int index) {
    return steps_.get(index);
  }
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  @Override
  public SpecificationStepProtoOrBuilder getStepsOrBuilder(
      int index) {
    return steps_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      writeString(output, 1, name_);
    }
    if (!getComponentBytes().isEmpty()) {
      writeString(output, 2, component_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      writeString(output, 3, description_);
    }
    if (status_ != SpecStatusProto.IMPLEMENTED.getNumber()) {
      output.writeEnum(4, status_);
    }
    for (int i = 0; i < steps_.size(); i++) {
      output.writeMessage(5, steps_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += computeStringSize(1, name_);
    }
    if (!getComponentBytes().isEmpty()) {
      size += computeStringSize(2, component_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += computeStringSize(3, description_);
    }
    if (status_ != SpecStatusProto.IMPLEMENTED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    for (int i = 0; i < steps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, steps_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SpecificationUpdatedProto)) {
      return super.equals(obj);
    }
    SpecificationUpdatedProto other = (SpecificationUpdatedProto) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getComponent()
        .equals(other.getComponent())) return false;
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (status_ != other.status_) return false;
    if (!getStepsList()
        .equals(other.getStepsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + COMPONENT_FIELD_NUMBER;
    hash = (53 * hash) + getComponent().hashCode();
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (getStepsCount() > 0) {
      hash = (37 * hash) + STEPS_FIELD_NUMBER;
      hash = (53 * hash) + getStepsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SpecificationUpdatedProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpecificationUpdatedProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpecificationUpdatedProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpecificationUpdatedProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpecificationUpdatedProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpecificationUpdatedProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpecificationUpdatedProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseWithIOException(PARSER, input);
  }
  public static SpecificationUpdatedProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpecificationUpdatedProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedWithIOException(PARSER, input);
  }
  public static SpecificationUpdatedProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpecificationUpdatedProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return parseWithIOException(PARSER, input);
  }
  public static SpecificationUpdatedProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SpecificationUpdatedProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code spectacle.events.SpecificationUpdatedProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spectacle.events.SpecificationUpdatedProto)
      SpecificationUpdatedProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpecificationUpdated.internal_static_spectacle_events_SpecificationUpdatedProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpecificationUpdated.internal_static_spectacle_events_SpecificationUpdatedProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpecificationUpdatedProto.class, Builder.class);
    }

    // Construct using io.gianluigip.spectacle.events.SpecificationUpdatedProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (alwaysUseFieldBuilders) {
        getStepsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      name_ = "";

      component_ = "";

      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;

      if (stepsBuilder_ == null) {
        steps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        stepsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SpecificationUpdated.internal_static_spectacle_events_SpecificationUpdatedProto_descriptor;
    }

    @Override
    public SpecificationUpdatedProto getDefaultInstanceForType() {
      return SpecificationUpdatedProto.getDefaultInstance();
    }

    @Override
    public SpecificationUpdatedProto build() {
      SpecificationUpdatedProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SpecificationUpdatedProto buildPartial() {
      SpecificationUpdatedProto result = new SpecificationUpdatedProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.component_ = component_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.description_ = description_;
      result.status_ = status_;
      if (stepsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          steps_ = java.util.Collections.unmodifiableList(steps_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.steps_ = steps_;
      } else {
        result.steps_ = stepsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SpecificationUpdatedProto) {
        return mergeFrom((SpecificationUpdatedProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SpecificationUpdatedProto other) {
      if (other == SpecificationUpdatedProto.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getComponent().isEmpty()) {
        component_ = other.component_;
        onChanged();
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000001;
        description_ = other.description_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (stepsBuilder_ == null) {
        if (!other.steps_.isEmpty()) {
          if (steps_.isEmpty()) {
            steps_ = other.steps_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStepsIsMutable();
            steps_.addAll(other.steps_);
          }
          onChanged();
        }
      } else {
        if (!other.steps_.isEmpty()) {
          if (stepsBuilder_.isEmpty()) {
            stepsBuilder_.dispose();
            stepsBuilder_ = null;
            steps_ = other.steps_;
            bitField0_ = (bitField0_ & ~0x00000002);
            stepsBuilder_ = 
              alwaysUseFieldBuilders ?
                 getStepsFieldBuilder() : null;
          } else {
            stepsBuilder_.addAllMessages(other.steps_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SpecificationUpdatedProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SpecificationUpdatedProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private Object component_ = "";
    /**
     * <code>string component = 2;</code>
     * @return The component.
     */
    public String getComponent() {
      Object ref = component_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        component_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string component = 2;</code>
     * @return The bytes for component.
     */
    public com.google.protobuf.ByteString
        getComponentBytes() {
      Object ref = component_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        component_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string component = 2;</code>
     * @param value The component to set.
     * @return This builder for chaining.
     */
    public Builder setComponent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      component_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string component = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearComponent() {
      
      component_ = getDefaultInstance().getComponent();
      onChanged();
      return this;
    }
    /**
     * <code>string component = 2;</code>
     * @param value The bytes for component to set.
     * @return This builder for chaining.
     */
    public Builder setComponentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      component_ = value;
      onChanged();
      return this;
    }

    private Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public String getDescription() {
      Object ref = description_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000001);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      description_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.spectacle.events.SpecStatusProto status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.spectacle.events.SpecStatusProto status = 4;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.spectacle.events.SpecStatusProto status = 4;</code>
     * @return The status.
     */
    @Override
    public SpecStatusProto getStatus() {
      @SuppressWarnings("deprecation")
      SpecStatusProto result = SpecStatusProto.valueOf(status_);
      return result == null ? SpecStatusProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.spectacle.events.SpecStatusProto status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(SpecStatusProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.spectacle.events.SpecStatusProto status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<SpecificationStepProto> steps_ =
      java.util.Collections.emptyList();
    private void ensureStepsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        steps_ = new java.util.ArrayList<SpecificationStepProto>(steps_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        SpecificationStepProto, SpecificationStepProto.Builder, SpecificationStepProtoOrBuilder> stepsBuilder_;

    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public java.util.List<SpecificationStepProto> getStepsList() {
      if (stepsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(steps_);
      } else {
        return stepsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public int getStepsCount() {
      if (stepsBuilder_ == null) {
        return steps_.size();
      } else {
        return stepsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public SpecificationStepProto getSteps(int index) {
      if (stepsBuilder_ == null) {
        return steps_.get(index);
      } else {
        return stepsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder setSteps(
        int index, SpecificationStepProto value) {
      if (stepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStepsIsMutable();
        steps_.set(index, value);
        onChanged();
      } else {
        stepsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder setSteps(
        int index, SpecificationStepProto.Builder builderForValue) {
      if (stepsBuilder_ == null) {
        ensureStepsIsMutable();
        steps_.set(index, builderForValue.build());
        onChanged();
      } else {
        stepsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder addSteps(SpecificationStepProto value) {
      if (stepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStepsIsMutable();
        steps_.add(value);
        onChanged();
      } else {
        stepsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder addSteps(
        int index, SpecificationStepProto value) {
      if (stepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStepsIsMutable();
        steps_.add(index, value);
        onChanged();
      } else {
        stepsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder addSteps(
        SpecificationStepProto.Builder builderForValue) {
      if (stepsBuilder_ == null) {
        ensureStepsIsMutable();
        steps_.add(builderForValue.build());
        onChanged();
      } else {
        stepsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder addSteps(
        int index, SpecificationStepProto.Builder builderForValue) {
      if (stepsBuilder_ == null) {
        ensureStepsIsMutable();
        steps_.add(index, builderForValue.build());
        onChanged();
      } else {
        stepsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder addAllSteps(
        Iterable<? extends SpecificationStepProto> values) {
      if (stepsBuilder_ == null) {
        ensureStepsIsMutable();
        addAll(
            values, steps_);
        onChanged();
      } else {
        stepsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder clearSteps() {
      if (stepsBuilder_ == null) {
        steps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        stepsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public Builder removeSteps(int index) {
      if (stepsBuilder_ == null) {
        ensureStepsIsMutable();
        steps_.remove(index);
        onChanged();
      } else {
        stepsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public SpecificationStepProto.Builder getStepsBuilder(
        int index) {
      return getStepsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public SpecificationStepProtoOrBuilder getStepsOrBuilder(
        int index) {
      if (stepsBuilder_ == null) {
        return steps_.get(index);  } else {
        return stepsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public java.util.List<? extends SpecificationStepProtoOrBuilder>
         getStepsOrBuilderList() {
      if (stepsBuilder_ != null) {
        return stepsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(steps_);
      }
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public SpecificationStepProto.Builder addStepsBuilder() {
      return getStepsFieldBuilder().addBuilder(
          SpecificationStepProto.getDefaultInstance());
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public SpecificationStepProto.Builder addStepsBuilder(
        int index) {
      return getStepsFieldBuilder().addBuilder(
          index, SpecificationStepProto.getDefaultInstance());
    }
    /**
     * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
     */
    public java.util.List<SpecificationStepProto.Builder>
         getStepsBuilderList() {
      return getStepsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        SpecificationStepProto, SpecificationStepProto.Builder, SpecificationStepProtoOrBuilder>
        getStepsFieldBuilder() {
      if (stepsBuilder_ == null) {
        stepsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            SpecificationStepProto, SpecificationStepProto.Builder, SpecificationStepProtoOrBuilder>(
                steps_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        steps_ = null;
      }
      return stepsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:spectacle.events.SpecificationUpdatedProto)
  }

  // @@protoc_insertion_point(class_scope:spectacle.events.SpecificationUpdatedProto)
  private static final SpecificationUpdatedProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SpecificationUpdatedProto();
  }

  public static SpecificationUpdatedProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpecificationUpdatedProto>
      PARSER = new com.google.protobuf.AbstractParser<SpecificationUpdatedProto>() {
    @Override
    public SpecificationUpdatedProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpecificationUpdatedProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpecificationUpdatedProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SpecificationUpdatedProto> getParserForType() {
    return PARSER;
  }

  @Override
  public SpecificationUpdatedProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

