// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spectacle/SpecificationUpdated.proto

package io.gianluigip.spectacle.events;

public interface SpecificationUpdatedProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spectacle.events.SpecificationUpdatedProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string component = 2;</code>
   * @return The component.
   */
  String getComponent();
  /**
   * <code>string component = 2;</code>
   * @return The bytes for component.
   */
  com.google.protobuf.ByteString
      getComponentBytes();

  /**
   * <code>string description = 3;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.spectacle.events.SpecStatusProto status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.spectacle.events.SpecStatusProto status = 4;</code>
   * @return The status.
   */
  SpecStatusProto getStatus();

  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  java.util.List<SpecificationStepProto>
      getStepsList();
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  SpecificationStepProto getSteps(int index);
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  int getStepsCount();
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  java.util.List<? extends SpecificationStepProtoOrBuilder>
      getStepsOrBuilderList();
  /**
   * <code>repeated .spectacle.events.SpecificationStepProto steps = 5;</code>
   */
  SpecificationStepProtoOrBuilder getStepsOrBuilder(
      int index);
}
