// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spectacle/SpecificationUpdated.proto

package io.gianluigip.spectacle.events;

public final class SpecificationUpdated {
  private SpecificationUpdated() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spectacle_events_SpecificationUpdatedProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spectacle_events_SpecificationUpdatedProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$spectacle/SpecificationUpdated.proto\022\020" +
      "spectacle.events\032#spectacle/Specificatio" +
      "nStatus.proto\032!spectacle/SpecificationSt" +
      "ep.proto\"\322\001\n\031SpecificationUpdatedProto\022\014" +
      "\n\004name\030\001 \001(\t\022\021\n\tcomponent\030\002 \001(\t\022\030\n\013descr" +
      "iption\030\003 \001(\tH\000\210\001\001\0221\n\006status\030\004 \001(\0162!.spec" +
      "tacle.events.SpecStatusProto\0227\n\005steps\030\005 " +
      "\003(\0132(.spectacle.events.SpecificationStep" +
      "ProtoB\016\n\014_descriptionB\"\n\036io.gianluigip.s" +
      "pectacle.eventsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SpecificationStatus.getDescriptor(),
          SpecificationStep.getDescriptor(),
        });
    internal_static_spectacle_events_SpecificationUpdatedProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spectacle_events_SpecificationUpdatedProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spectacle_events_SpecificationUpdatedProto_descriptor,
        new String[] { "Name", "Component", "Description", "Status", "Steps", "Description", });
    SpecificationStatus.getDescriptor();
    SpecificationStep.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
